name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: NuGet Restore
      working-directory: ./backend/
      run: dotnet restore

    - name: Build
      working-directory: ./backend/
      run: dotnet build -c Release --no-restore

    # - name: Install EF Core CLI
    #   run: dotnet tool install --global dotnet-ef

    # - name: Build and run EF Core migrations
    #   working-directory: ./backend/GameWave.API/
    #   run: dotnet ef database update --connection "$CONNECTION_STRING"
    #   env:
    #     CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

    - name: Publish
      working-directory: ./backend/
      run: dotnet publish GameWave.API/GameWave.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/deploy/backend --no-restore
    
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: gamewave-api
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A788D754AF8AAA4B5CF3EB5A6D8E4D16 }}
        package: ${{env.DOTNET_ROOT}}/deploy/backend

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      working-directory: ./frontend/
      run: npm ci

    - name: Build
      working-directory: ./frontend/
      run: npm run build

    - name: Deploy to Azure Static Web Apps
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_HILL_089A7DF10 }}
        repo_token: ${{ secrets.GAMEWAVE_REPO_TOKEN }}
        action: "upload"
        app_location: "/frontend"
        api_location: ""
        output_location: "dist"
