name: Deploy to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: NuGet Restore
      run: dotnet restore
      working-directory: ./backend/src/

    - name: Build
      run: dotnet build -c Release --no-restore
      working-directory: ./backend/src/

    - name: Publish
      run: dotnet publish FinalBoss.Api/FinalBoss.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/_api --no-restore
      working-directory: ./backend/src/
    
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: finalboss-api
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A788D754AF8AAA4B5CF3EB5A6D8E4D16 }}
        package: ${{env.DOTNET_ROOT}}/_api

